import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'; // Import the CSS for ToastContainer
import { SessionWrapper } from "@/components/auth/SessionWrapper";
import Footer from "@/components/component/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <ToastContainer
        position="top-right"
        
      />
      <SessionWrapper>
        {children}
        <Footer/>
      </SessionWrapper>
        </body>
    </html>
  );
}
